name: Check step 6, Production deployment cleanup

# This step sets STEP to 7
# This step closes <details id=6> and opens <details id=7>

# This will run after the "Configure Azure environment" workflow
# completes on the production-deployment-workflow branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Configure Azure environment"]
    types: [completed]
    branches: [production-deployment-workflow]

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  # The purpose of this job is to output the current step number 
  # (retreived from the STEP file). This output variable can
  # then be referenced in other jobs and used in conditional 
  # expressions.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_destroy_completed:
    name: On destroy completed
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 6 (see update-step.sh)
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 6 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Update README to close <details id=6>
      # and open <details id=7>
      # and set STEP to '7'
      - name: Update to step 7
        run: ./.github/script/update-step.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_STEP: 6
          TO_STEP: 7
